services:
  rag_pipeline_server:
    build:
      context: ./rag
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # - LLM_API_HOST=llm_api
      # - LLM_API_PORT=8500
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    # depends_on:
    #   - llm_api
    env_file:
      - .env

  node_server:
    build:
      context: ./node_server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MODEL_SERVER_HOST=rag_pipeline_server
      - MODEL_SERVER_PORT=8000
    depends_on:
      - rag_pipeline_server


  # llm_api:
  #   build:
  #     context: ./llm_api
  #     dockerfile: Dockerfile
  #     args:
  #       HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
  #       MODEL_NAME: ${MODEL_NAME}
  #   environment:
  #     - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
  #     - MODEL_NAME=${MODEL_NAME}
  #   ports:
  #     - "8500:8500"
  #   volumes:
  #     - ./models:/models
  #   env_file:
  #     - .env

