services:
  rag_pipeline_server:
    build:
      context: ./rag
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    # Remove the depends_on line here
    # depends_on:
    #   - node_server

  node_server:
    build:
      context: ./node_server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MODEL_SERVER_HOST=rag_pipeline_server
      - MODEL_SERVER_PORT=8000
    depends_on:
      - rag_pipeline_server  # Node server depends on the RAG server
