version: '3'
services:
  node_server:
    build: ./node_server
    ports:
      - "5000:5000"
    environment:
      - MODEL_SERVER_HOST=rag_pipeline_server
      - MODEL_SERVER_PORT=8000
    depends_on:
      - rag_pipeline_server

  rag_pipeline_server:
    build: ./rag_pipeline_server
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
